service: hellow-world-python-lambda

provider: 
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: hellow-world-python
    handler: lambda.hellowWorld1
    description: test-lambda
    timeout: 30
    memorySize: 128
    events:
      - schedule: "rate(6 hours)"
    package: 
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package.json"
        - "!package-lock.json"
  
  listLambda:
    name: python-List
    handler: lambda.secondLambda
    description: test-lambda
    timeout: 30
    memorySize: 128
    events:
      - schedule: "rate(6 hours)"
    package: 
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package.json"
        - "!package-lock.json"